### ISSUE TITLE
Error while installing the extension

### ISSUE THREAD

**Issue by sh-o-aib** [aress31/burpgpt#12]
I accurately, followed compilation steps, but while installing burpgpt-all.jar file from ./lib/build/libs/ I get folling error:

java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:398)
	at burp.l5y.k(Unknown Source)
	at burp.l5y.<init>(Unknown Source)
	at burp.sg1.Z(Unknown Source)
	at burp.lmh.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Pluslg** [comment]
Compile by the kali-linux distro in the windows wsl because the wsl does not give an error.
