### ISSUE TITLE
[BUG] Error when load burpgpt plugin

### ISSUE THREAD

**Issue by EwanSunn** [aress31/burpgpt#4]
# Description
When I load the plugin there is an error.

# Environment

- OS: Mac OS 13.3 (22E252)
- Java version: "1.8.0_201"
- Burp Suite version:Professional 2022.9

# Error Message
```
java.lang.AbstractMethodError: Receiver class burp.MyBurpExtension does not define or inherit an implementation of the resolved method 'abstract void initialise(burp.api.montoya.MontoyaApi)' of interface burp.api.montoya.BurpExtension.
	at burp.gre.m(Unknown Source)
	at burp.s4i.D(Unknown Source)
	at burp.s4d.lambda$initialiseOnNewThread$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by HB666666** [comment]
Need the latest version of burpsuite, I tried 2023 2 and it doesn't work. There is no problem with the java 8 environment
![image](https://user-images.githubusercontent.com/110554291/231062724-88cf0bff-3c07-4b39-b907-deea3ea05120.png)
