### ISSUE TITLE
[BUG] When loading this plugin, I receive a ClassNotFoundException.

### ISSUE THREAD

**Issue by MUYU212** [aress31/burpgpt#6]
- OS: Macos 13
- java version "11.0.18" 2023-01-17 LTS
- Burp Suite version: 2022.3.9 Professional

My Burp is giving me the following notification, and I have followed the steps for compilation.

java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at burp.cs1.a(Unknown Source)
	at burp.cs1.<init>(Unknown Source)
	at burp.a6l.a(Unknown Source)
	at burp.c7v.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by hu185396** [comment]
+1

**Comment by rizaust** [comment]
+1

**Comment by tcqq123** [comment]
+1

**Comment by black0sword** [comment]
+1

**Comment by germer-19** [comment]
+1

**Comment by HB666666** [comment]
The latest version of burpsuite is required. I tried the 2023 2 version and it didn’t work.

**Comment by MUYU212** [comment]
But when I load this plugin, the settings interface for GPT still cannot pop up.
<img width="1485" alt="image" src="https://user-images.githubusercontent.com/40883822/231078795-a6d68e2b-ee7d-4960-baea-8fea0f819314.png">

**Comment by HB666666** [comment]
> 

I don't know if your burpsuit is the 2023 3 version, but I imported it successfully in the burpsuit 2023 3 version and it shows up in the settings window

**Comment by aress31** [comment]
https://github.com/aress31/burpgpt/issues/5
