### ISSUE TITLE
[BUG] When loading this plugin, I receive a ClassNotFoundException.

### ISSUE THREAD

**Issue by highgerms** [aress31/burpgpt#8]
Description

When I load the plugin there is an error.
Environment

    OS: windows11
    Java version: "18.0.2"
    Burp Suite version:Professional v2022.3
    
    java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:488)
	at java.base/java.lang.Class.forName(Class.java:467)
	at burp.i9a.a(Unknown Source)
	at burp.i9a.<init>(Unknown Source)
	at burp.ijn.a(Unknown Source)
	at burp.c7p.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

    
    
![图片](https://user-images.githubusercontent.com/50609840/230886354-d67fb8c7-9d1e-4db5-bf2e-94518f87b5f0.png)

**Comment by Zilong404** [comment]
我也是这个问题，有人解答吗

**Comment by hackfox666** [comment]
+1

**Comment by MonaQuimbamba** [comment]
same for me

**Comment by Nintyhundred** [comment]
same  for me too

**Comment by chesterblue** [comment]
+1

**Comment by HB666666** [comment]
The latest version of burpsuite is required.

**Comment by HB666666** [comment]
The latest version of burpsuite is required. 
![image](https://user-images.githubusercontent.com/110554291/231062523-3af55b3f-1015-4e93-8fbf-b988e46c9f74.png)

**Comment by HB666666** [comment]
I don't know how to use it, the community can import it, as for how to use it, my friends and I have studied it for a while and gave up without finding a way to use it.

**Comment by aress31** [comment]
https://github.com/aress31/burpgpt/issues/5
